name: Update Instagram Followers

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install instaloader

      - name: Run update script
        run: python scripts/update_followers.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add public/data
          git commit -m "Update followers" || echo "No changes to commit"
          git push
