name: Update Instagram Followers

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-followers:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: insta-followers
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U devuser -d insta-followers"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: insta-followers
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Wait for database
        run: |
          python - <<'PY'
          import os
          import time

          import psycopg

          host = os.environ["POSTGRES_HOST"]
          port = int(os.environ["POSTGRES_PORT"])
          user = os.environ["POSTGRES_USER"]
          password = os.environ["POSTGRES_PASSWORD"]
          dbname = os.environ["POSTGRES_DB"]

          for attempt in range(1, 31):
              try:
                  psycopg.connect(
                      host=host,
                      port=port,
                      user=user,
                      password=password,
                      dbname=dbname,
                  ).close()
                  break
              except psycopg.OperationalError as exc:
                  if attempt == 30:
                      raise SystemExit(f"Database not ready: {exc}")
                  time.sleep(2)
          PY

      - name: Seed database from JSON snapshots
        run: python scripts/import_data.py

      - name: Run update script
        run: python scripts/update_followers.py

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add public/data
          git commit -m "Update followers" || echo "No changes to commit"
          git push
